version: '3'

services:
  app:
    build: .
    depends_on:
      - kong
    volumes:
      - .:/work

  kong:
    image: kong:0.14.1-centos
    depends_on:
      - db
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=db
      - KONG_PG_PORT=5432
      - KONG_PG_DATABASE=kong_db
      - KONG_PG_USER=kong_user
      - KONG_PG_PASSWORD=53cr3tp455v0rd
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
      - KONG_PLUGINS=bundled
      - KONG_NGINX_DAEMON=off
      - KONG_LOG_LEVEL=debug
      - KONG_ADMIN_ACCESS_LOG=/proc/1/fd/1
      - KONG_ADMIN_ERROR_LOG=/proc/1/fd/1
      - KONG_PROXY_ACCESS_LOG=/proc/1/fd/1
      - KONG_PROXY_ERROR_LOG=/proc/1/fd/1
      - KONG_NGINX_WORKER_PROCESSES=1
    command: 'bash -c "sleep 2 && kong migrations up && kong start"'

  db:
    image: postgres
    environment:
      - POSTGRES_DB=kong_db
      - POSTGRES_USER=kong_user
      - POSTGRES_PASSWORD=53cr3tp455v0rd
